---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.0.11 webserver wordpress.4labs.example chat.4labs.example
        - 172.16.0.12 graylog
        - 172.16.0.13 kibana kibana.4labs.example

    - name: Adicionar usuario suporte
      user:
        name: suporte
        shell: /bin/bash
        password : $1$QbUARykG$p2nthVG8AkDvabKPHwboa1
        
    - name: Criando o arquivo 98_4linux
      copy:
        src: files/98_4linux
        dest: /etc/sudoers.d
        mode: 0644

    - name: Instalando pacotes de dependencias para o curso
      apt:
        name: ['unzip', 'wget', 'elinks', 'rsync', 'vim']

    - name: Criando diretorio /opt/filebeat
      synchronize:
        src: files/filebeat
        dest: /opt

    - name: Criando diretorio /opt/logstash
      synchronize:
        src: files/logstash
        dest: /opt

    - name: Criando diretorio /opt/metricbeat
      synchronize:
        src: files/metricbeat
        dest: /opt

    - name: Criando diretorio /opt/nginx
      synchronize:
        src: files/nginx
        dest: /opt

    - name: Criando o arquivo syslog-tls.conf
      copy:
        src: files/client/syslog-tls.conf
        dest: /opt
        mode: 0644
